<a href="https://colab.research.google.com/github/ngocnhihophuong2599-max/TH_Deep/blob/main/tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import tensorflow as tf

print("=== PHẦN 1: BÀI TẬP NUMPY ===")
arr1 = np.random.randint(0, 21, size=(3, 3))
print(f"1. Mảng ngẫu nhiên arr1:\n{arr1}")
print(f"   Tất cả các phần tử trong arr1 đều khác 0? -> {np.all(arr1 != 0)}\n")

arr2 = np.random.randint(0, 21, size=(3, 3))
print(f"2. Mảng ngẫu nhiên arr2:\n{arr2}")
print(f"   Có ít nhất một phần tử trong arr2 khác 0? -> {np.any(arr2 != 0)}\n")

v1 = np.array([10, 20, 30])
v2 = np.array([15, 20, 25])
print("3. So sánh các mảng 1 chiều:")
print(f"   - np.greater (v1 > v2): {np.greater(v1, v2)}")
print(f"   - np.greater_equal (v1 >= v2): {np.greater_equal(v1, v2)}")
print(f"   - np.less (v1 < v2): {np.less(v1, v2)}")
print(f"   - np.less_equal (v1 <= v2): {np.less_equal(v1, v2)}\n")

arr4 = np.hstack((np.ones(10), np.zeros(10), np.full(10, 5)))
print(f"4. Mảng kết hợp [10 số 1, 10 số 0, 10 số 5]:\n{arr4}\n")

arr5 = np.arange(30, 71, 2)
print(f"5. Mảng số nguyên chẵn từ 30 đến 70:\n{arr5}\n")

matrix_identity = np.identity(3)
print(f"6. Ma trận đơn vị 3x3:\n{matrix_identity}\n")


print("=== PHẦN 2: BÀI TẬP TENSORFLOW CƠ BẢN ===")

t1 = tf.zeros([2, 3])
print(f"1. Tensor zeros [2, 3]:\n{t1.numpy()}\n")

X = [[1, 2, 3], [4, 5, 6]]
t2 = tf.zeros_like(X)
print(f"2. Tensor zeros_like X:\n{t2.numpy()}\n")

t3 = tf.fill([3, 2], 5)
print(f"3. Tensor fill 5 kích thước [3, 2]:\n{t3.numpy()}\n")

t4 = tf.linspace(5.0, 10.0, 50)
print(f"4. Tensor 1D 50 phần tử từ 5 đến 10:\n{t4.numpy()}\n")

t5 = tf.range(10, 101, delta=2)
print(f"5. Tensor range từ 10 đến 100:\n{t5.numpy()}\n")

t6 = tf.random.normal([3, 2], mean=0.0, stddev=2.0)
print(f"6. Tensor Normal [3, 2]:\n{t6.numpy()}\n")

t7 = tf.random.uniform([3, 2], minval=0.0, maxval=2.0)
print(f"7. Tensor Uniform [3, 2]:\n{t7.numpy()}\n")

X_8 = tf.constant([[1, 2], [3, 4], [5, 6]])
t8 = tf.random.shuffle(X_8)
print(f"8. Tensor sau khi shuffle dòng:\n{t8.numpy()}\n")

t9_origin = tf.random.normal([10, 10, 3])
t9_crop = tf.image.random_crop(t9_origin, size=[5, 5, 3])
print(f"9. Kích thước gốc: {t9_origin.shape} -> Sau khi crop: {t9_crop.shape}\n")

# 10. Tạo hai tensor 1D x, y. Trả về x+y nếu x<y, ngược lại x-y
x_10 = tf.constant([2, 8, 4, 1, 9])
y_10 = tf.constant([5, 3, 4, 7, 6])
condition = tf.less(x_10, y_10)
t10 = tf.where(condition, x_10 + y_10, x_10 - y_10)
print(f"10. x: {x_10.numpy()} | y: {y_10.numpy()}")
print(f"    Kết quả phép toán điều kiện: {t10.numpy()}\n")

x_11 = tf.random.uniform([3, 3], minval=5, maxval=10, dtype=tf.int32)
y_11 = tf.random.uniform([3, 3], minval=15, maxval=20, dtype=tf.int32)
diag_vector = tf.linalg.diag_part(x_11)
x_diagonal_matrix = tf.linalg.diag(diag_vector)
result_11 = x_diagonal_matrix + y_11
print(f"11. Ma trận đường chéo từ x:\n{x_diagonal_matrix.numpy()}")
print(f"    Kết quả cộng với y:\n{result_11.numpy()}\n")


print("=== PHẦN 3: TENSORFLOW GRAPH & MODELS ===")

@tf.function
def math_graph_operations(tensor_a, tensor_b):
    add_res = tf.add(tensor_a, tensor_b)
    sub_res = tf.subtract(tensor_a, tensor_b)
    mul_res = tf.multiply(tensor_a, tensor_b)
    div_res = tf.divide(tensor_a, tensor_b)
    return add_res, sub_res, mul_res, div_res

a_12 = tf.random.normal([3, 2, 2])
b_12 = tf.random.normal([3, 2, 2])
add_r, sub_r, mul_r, div_r = math_graph_operations(a_12, b_12)
print("12. Đã thực thi tính toán cộng, trừ, nhân, chia ma trận (3,2,2) trong Graph.\n")

class AddModel(tf.Module):
    def __call__(self, x, y):
        return tf.add(x, y)

class MathModel(tf.Module):
    def __call__(self, x, y):
        return tf.subtract(x, y), tf.multiply(x, y)

class RectanglePerimeterModel(tf.Module):
    def __call__(self, a, b):
        return tf.multiply(tf.add(a, b), 2.0)

class BoxAreaModel(tf.Module):
    def __call__(self, a, b, c):
        s_xung_quanh = tf.multiply(tf.multiply(tf.add(a, b), c), 2.0)
        s_toan_phan = tf.add(tf.multiply(tf.multiply(a, b), 2.0), s_xung_quanh)
        return s_toan_phan

class TrapezoidSideValidationModel(tf.Module):
    def __call__(self, ab, cd, ad, bc):
        cond1 = tf.equal(ad, bc)
        cond2 = tf.equal(ab, cd)
        return tf.logical_and(cond1, cond2)

class TrapezoidBaseValidationModel(tf.Module):
    def __call__(self, ad_equal_bc, ad_parallel_bc):
        return tf.logical_and(ad_equal_bc, ad_parallel_bc)

class TriangleMidpointProofModel(tf.Module):
    def __call__(self, am, mb, mn_parallel_bc):
        is_m_midpoint = tf.equal(am, mb)
        proof_result = tf.logical_and(is_m_midpoint, mn_parallel_bc)
        return proof_result
rect_model = RectanglePerimeterModel()
box_model = BoxAreaModel()
proof_model = TriangleMidpointProofModel()

print(f"15. Chu vi hình chữ nhật (a=10, b=20): {rect_model(10.0, 20.0).numpy()}")
print(f"16. Diện tích toàn phần hình hộp (a=2, b=3, c=4): {box_model(2.0, 3.0, 4.0).numpy()}")
print(f"19. Kết quả chứng minh hình học tam giác: {proof_model(tf.constant(4.0), tf.constant(4.0), tf.constant(True)).numpy()}")

=== PHẦN 1: BÀI TẬP NUMPY ===
1. Mảng ngẫu nhiên arr1:
[[20 14 17]
 [ 3 16 11]
 [ 3 18  9]]
   Tất cả các phần tử trong arr1 đều khác 0? -> True

2. Mảng ngẫu nhiên arr2:
[[18  3 18]
 [ 7 17  8]
 [10 13 14]]
   Có ít nhất một phần tử trong arr2 khác 0? -> True

3. So sánh các mảng 1 chiều:
   - np.greater (v1 > v2): [False False  True]
   - np.greater_equal (v1 >= v2): [False  True  True]
   - np.less (v1 < v2): [ True False False]
   - np.less_equal (v1 <= v2): [ True  True False]

4. Mảng kết hợp [10 số 1, 10 số 0, 10 số 5]:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]

5. Mảng số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]

6. Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

=== PHẦN 2: BÀI TẬP TENSORFLOW CƠ BẢN ===
1. Tensor zeros [2, 3]:
[[0. 0. 0.]
 [0. 0. 0.]]

2. Tensor zeros_like X:
[[0 0 0]
 [0 0 0]]

3. Tensor fill 5 kích thước [3, 2]:
[[5 5]
 [5 5]
 [5 5]]

4. Tensor 1D 5